Homework1
made-ml-in-prod-2021/mivankin pull request #2
Opened 2021-05-08 11:30 UTC by mivankin

Проект реализован на основе датасета https://www.kaggle.com/ronitf/heart-disease-uci , как и предлагалось в задании. 

Для этого изначально провел анализ данных, сформировал отчет с помощью pandas proffiling и сгенерировал синтетические данные в ноутбуке, который расположен в ../src/notebooks/ml_in_prod.ipynb 

Обучал на основе логистической регрессии, параметры модели и стратегий обучения можно указать в конфигурационном файле ../src/train_config.yaml

Проект имеет модульную структуру и создан на основе CookieCutter, запуск возможен через python src/ml_in_prod1.py Подробное описание указано в https://github.com/made-ml-in-prod-2021/mivankin/blob/homework1/ml_project/README.md

Основной функционал реализован в /src/models/model.py Был создан класс UCImodel, позволяющий решать следующие задачи:
1) Загрузка датасета
2) Обучение модели
3) Дамп модели
4) Загрузка дампа модели
5) Предсказания на основе обученной модели
6) Расчет AUC score 
Основной моделью использовалась логистическая регрессия

В проекте использовались логгеры, один для сообщений уровня INFO, второй для ERROR, Отчеты можно найти в ../src/heart_dissease_uci.info, ../src/heart_dissease_uci.log
Так как использовалась Hydra, то она параллельно перехватывает логи и выводит их для удобства в консоль.

Для пользы обучения был реализован свой трансформер, который отбирает из датасета только нужные для обучения фичи и возвращает новый датасет. Реализация находится в ../src/features/transformer.py

Кроме этого, был реализован класс для генерации синтетических данных. Основная идея заключается в расчете среднего и дисперсии для каждой фичи, которые хранятся в экземпляре класса. Для генерации данных используется сэмплирование из нормального распределения на основе рассчитанных среднего и дисперсии. Для дискретных данных (в проекте подразумевалось, что это категориальные данные) сэмплированные данные приводятся к целочисленному типу. Дополнительно проводится проверка на адекватность сгенерированных данных с использованием функции ks_2samp - если d_value = 1 считаем, что реальные и синтетические данные из разных распределений (спойлер: если вы сравниваете сгенерированные данные и реальные данные, на основе которых происходила генерация такого не будет никогда). Для синтетических данных auc 0.49-0.5

Были реализованы тесты для каждой функции в отдельности для всего пайплайна. Кроме этого, тесты написаны для генератора синтетических данных. Тесты находятся в /src/tests. Запуск возможен через pytest --cov -v . test_fake_data.py
Тесты находятся в /src/tests/ Старался писать по TDD - сначала реализация теста, потом реализация функционала, получается долго, но потом сразу все работает и потом проще в поддержке.

Проверьте, пожалуйста:)

2021-05-09 17:07 UTC, vladimirzenin approved these changes
В целом работа выполнена на более высоком уровне чем моя, поэтому я не все сходу понял.
Замечания:
1. Не увидел альтернативного конфига для обучения. В задании было написано "Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель". Но это не существенно, вижу что ничего не мешает добавить второй.
2. По п.13 "напишите функцию predict, которая примет на вход артефакт/ы от обучения", вижу что описано получение предсказания, но не вижу переиспользования артефактов. Т.е. ранее натренированной и сохраненной модели. В этом плане пункт выполнен частично. Если я все правильно увидел, тут можно вычесть 1 балл.

Итог: 33-34 балла.

2021-05-10 16:53 UTC, mivankin commented
Спасибо за ревью. Я добавил следующий функционал:
1) Теперь с помощью валидного 'train_config.yaml' возможно обучить кроме модели логистической регрессии (LogisticRegression()) модель наивного байесовского классификатора (GaussianNB()). Конфигурация для него в 'train_config_gaussian.yaml', чтобы его использовать, нужно переименовать в 'train_confg.yaml'. Таким образом сейчас на основе вложенных конфигураций есть возможность:
- оставить все по умолчанию и обучать логистическую регрессию с оптимизатором 'liblinear';
- использовать 'train_config.yaml' с логистической регрессией и оптимизатором 'saga';
- использовать наивный байесовский классификатор из 'train_config_gaussian.yaml'.

2) По поводу функции predict не совсем понял, так как в https://github.com/made-ml-in-prod-2021/mivankin/blob/homework1/ml_project/src/models/model.py в функции callback_predict есть вызов метода uci_model = load_model(arguments.load_model_path), который подгружает обученную модель с локального диска

2021-05-11 21:19 UTC, ol-ga-00 commented
Файл .gitkeep обычно помещают в пустую директорию, дабы сказать "директорию пустая, но она нам нужна; пусть гит знает о существовании этой директории"
Если в директории помимо .gitkeep есть и другие файлы, то .gitkeep теряет свою актуальность. Прошу удалить такие файлы, где они не актуальны.

2021-05-11 21:25 UTC, ol-ga-00 commented
Необходимо разделять скрипты от других файлов. 
Рекомендую в папке src/ (source) оставить только py файлы, а всё остальное вынести. В частности, из src/ необходимо вынести data/ и конфигурационные yaml файлы (в config/, например). Тем более в репозитории присутствует setup.py, а значит предполагается создание пакета и его дальнейшее использование.

2021-05-11 21:26 UTC, ol-ga-00 commented
tests/data/ и src/data/ дублируют друг друга?

2021-05-11 22:14 UTC, ol-ga-00 reviewed
Плохо коммитить бинарники (src/model.pkl)
Он точно здесь нужен? Вы хотите, чтобы кто-то взял его, и сейчас нет другого способа (другого хранилища), откуда его можно было бы взять?

2021-05-11 22:14 UTC, ol-ga-00 commented on ml_project/src/models/model.py
> +            lg.lgr.error("ParserError, check dataset type, csv dataset expected")
Код пока не запускала, но я правильно понимаю, что если в конфиге что-то указать некорректно, то код будет падать с непонятными ошибками, так как везде в блоке except пишется лог error, а не происходит падение. 
Например, если попадём в этот except, то значит self.dataset не изменил своё значение и он по прежнему будет равен None. И тогда на строчках 88-97 произойдёт падение с ошибкой типа "None.age ... ".
Вам, как разработчику, будет понятно, где произошло падение, но другим не будет понятно, и тогда им придётся лезть в исходники (в этот код). Но ведь логи на то и логи, они должны сказать "то-то пошло не так, поправь вот это вот вот здесь". 
Вы согласны со мной?

2021-05-11 22:14 UTC, ol-ga-00 commented on ml_project/src/models/model.py
> +            lg.lgr.error("ParserError, check dataset type, csv dataset expected")
И это относится ко всем блокам try except

2021-05-11 22:14 UTC, ol-ga-00 commented on ml_project/src/models/model.py
> +        return _exec_value
В коде нигде не проверяется значение _exec_value (тест не считается). 
То есть действительно в except пишутся только логи, а падение происходит на других строчках с непонятным текстом ошибки (не с пользовательским)

2021-05-11 22:18 UTC, ol-ga-00 reviewed
В отношении тестов рекомендую изучить статью https://habr.com/ru/post/448786/
Обратить внимание следует на "Обмен Fixtures через conftest.py" и "Спецификация областей(Scope) Fixture"

2021-05-11 22:18 UTC, ol-ga-00 commented on ml_project/tests/test_model.py
> +	test_sample.to_csv('test_fake.csv')
Это сохранение каждый раз будет перезаписывать существующий csv файл. 
Предлагаю удалить существующий csv файл

2021-05-11 22:29 UTC, ol-ga-00 requested changes

2021-05-11 22:29 UTC, ol-ga-00 commented on ml_project/tests/test_model.py
> +	test_model = model.UCImodel(test_params.test_model, test_params.test_solver, test_params.test_reg, test_params.test_max_iter, test_params.test_seed)
Строчки с 106 и до 112 часто всегда и везде повторяются!
Предлагаю test_params вынести в фикстуру и test_model вынести в фикстуру

2021-05-11 22:29 UTC, ol-ga-00 commented on ml_project/tests/test_model.py
> +def test_all_build_model():
Не вижу существенной разницы между этим тестом и тестом test_auc()
Предлагаю в этом тесте проверить работоспособность функции callback_build

2021-05-11 22:29 UTC, ol-ga-00 commented on ml_project/src/models/model.py
> +        for name, X, y, model in [
name нигде не используется
вместо model сразу можно писать self.model

2021-05-12 19:49 UTC, mivankin commented
Спасибо огромное за ревью, я постарался исправить все описанные недочеты. Вот что я сделал:
1) Убрал ненужные .gitkeep из не пустых директорий;
2) Создал отдельную директорию cofigs в которой теперь располагаются конфигурации
3) Логи теперь в отдельно папке outputs\logs
4) tests/data/ и src/data/ больше не дублируют друг друга, данные располагаются в директории data/raw
5) Генератор синтетических данных перенес в tests/features
6) Прописанные пути убрал из кода, теперь они грузятся только из конфигураций
7) Логи сделал более подробными, с f'string и передачей в нее необходимых параметров. 
8) При исключениях генерируется NotImplementedError, чтобы работа скрипта прерывалась и не падала дальше с непонятными ошибками и можно было разобраться в чем проблема на основе логов.
9) Спасибо, я прочитал статью о fixtures и теперь использую этот механизм в тестах со scope='session', чтобы за время тестирования код, который дублировался, выполнялся один раз, этого достаточно.
10) Все бинарники и временные csv файлы удалил из коммита
11) Дополнительно в тестах переделал реализацию test_all_build_model и добавил test_all_predict_model. В этих тестах прогоняется код на синтетических данных и из записей логгера делается вывод о том, корректно ли выполнились соответствующие методы callback_build, callback_predict или нет.

Надеюсь, я ничего не забыл и исправил, все что было необходимо:)
Посмотрите, пожалуйста, еще раз

2021-05-15 11:52 UTC, ol-ga-00 requested changes

2021-05-15 22:15 UTC, mivankin commented on ml_project/tests/test_model.py
> +    error_value = test_model.split_and_fit()
Спасибо!

2021-05-15 22:18 UTC, mivankin commented
Спасибо за комментарии и предложения. 
1) Я исправил метод test_fit_with_load_data, чтобы проверять, что self.X_train, self.X_test, self.Y_train, self.Y_test в test_model теперь не None. 
2) Кроме этого сделал так, чтобы функция split_and_fit  ничего не возвращала

P.S. Теперь учту, что не стоит для тестов возвращать какие то данные из функции, которые потом нигде кроме теста не используются

2021-05-16 06:08 UTC, ol-ga-00 requested changes
Забыла в тот раз написать

В .gitignore нужно добавить .pytest_cache. Эту директорию коммитеть не нужно

2021-05-16 09:59 UTC, mivankin commented
Удалил из коммита директорию pytest_cache. Посмотрите еще раз, пожалуйста

2021-05-16 19:50 UTC, ol-ga-00 approved these changes
Ставлю 34 балла

2021-05-16 19:55 UTC, merged

2021-05-16 19:55 UTC, mivankin commented
Спасибо!